include: package:lints/recommended.yaml
analyzer:
 strong-mode:
  implicit-casts: false
linter:
 rules:
   avoid_returning_null_for_future: true
   avoid_setters_without_getters: true
   cancel_subscriptions: true
   close_sinks: true
   no_adjacent_strings_in_list: true
   omit_local_variable_types: true
   only_throw_errors: true
   prefer_relative_imports: true
   prefer_single_quotes: true
   sort_pub_dependencies: true
   test_types_in_equals: true
   unawaited_futures: true
   unnecessary_parenthesis: true
   unnecessary_statements: true
