analyzer:

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
   # Error Rules
   - avoid_empty_else
   #- avoid_slow_async_io
   - cancel_subscriptions
   - close_sinks
#   - comment_references
   - control_flow_in_finally
   - empty_statements
   - hash_and_equals
   - invariant_booleans
   - iterable_contains_unrelated_type
   - literal_only_boolean_expressions
   - no_adjacent_strings_in_list
   - no_duplicate_case_values
   - test_types_in_equals
   - throw_in_finally
   - unrelated_type_equality_checks
   - valid_regexps

   # Style Rules
   #- always_declare_return_types
#   - always_put_control_body_on_new_line
   - always_require_non_null_named_parameters
   #- always_specify_types
   - annotate_overrides
   #- avoid_annotating_with_dynamic
   #- avoid_as
   #- avoid_catches_without_on_clauses
   - avoid_catching_errors
   #- avoid_classes_with_only_static_members
   #- avoid_function_literals_in_foreach_calls
   - avoid_init_to_null
   - avoid_null_checks_in_equality_operators
   #- avoid_positional_boolean_parameters
   - avoid_return_types_on_setters
   #- avoid_returning_null
   - avoid_returning_this
   - avoid_setters_without_getters
   #- avoid_types_on_closure_parameters
   - await_only_futures
   - camel_case_types
#   - cascade_invocations
   - constant_identifier_names
   #- directives_ordering
   - empty_catches
   - empty_constructor_bodies
   #- implementation_imports
   #- join_return_with_assignment
   - library_names
   - library_prefixes
   - non_constant_identifier_names
   #- omit_local_variable_types
   #- one_member_abstracts
   #- only_throw_errors
   - overridden_fields
   #- package_api_docs
   - package_prefixed_library_names
   #- parameter_assignments
   - prefer_adjacent_string_concatenation
   - prefer_collection_literals
   - prefer_conditional_assignment
   #- prefer_const_constructors
   #- prefer_constructors_over_static_methods
   - prefer_contains
   #- prefer_expression_function_bodies
   - prefer_final_fields
   #- prefer_final_locals
   - prefer_foreach
   - prefer_function_declarations_over_variables
   #- prefer_initializing_formals
#   - prefer_interpolation_to_compose_strings
   - prefer_is_empty
   - prefer_is_not_empty
   #- public_member_api_docs
   - recursive_getters
   - slash_for_doc_comments
   #- sort_constructors_first
   #- sort_unnamed_constructors_first
   #- type_annotate_public_apis
   - type_init_formals
   - unawaited_futures
   - unnecessary_brace_in_string_interps
   #- unnecessary_getters_setters
   #- unnecessary_lambdas
   - unnecessary_null_aware_assignments
   - unnecessary_null_in_if_null_operators
   #- unnecessary_overrides
   - unnecessary_this
   - use_rethrow_when_possible
   #- use_setters_to_change_properties
   #- use_string_buffers
   - use_to_and_as_if_applicable

   # Pub Rules
   - package_names