name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests ${{matrix.sdk}} on ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ['beta']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - uses: actions/checkout@v2
      - run: dart --version
      - run: dart pub get
      - run: dart analyze --fatal-infos .
      - run: dart example/download_chromium.dart
      - name: install required packages
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update; sudo apt-get install -yq --no-install-recommends libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3
          export DISPLAY=:99.0
          Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
      - run: xvfb-run --auto-servernum dart test -P ci --platform vm --concurrency=1
        if: runner.os == 'Linux'
      - run: dart test -P ci --platform vm --concurrency=1
        if: runner.os != 'Linux'
        env:
          PUPPETEER_SKIP_GOLDEN_COMPARISON: 'true'
      - run: dart tool/prepare_submit.dart
      - name: "check for uncommitted changes"
        run: |
          git diff --exit-code --stat -- . \
          || (echo "##[error] found changed files after build. please run 'dart tool/prepare_submit.dart'" \
                   "and check in all changes" \
              && exit 1)
        shell: bash
