name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests ${{matrix.sdk}} on ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ['stable']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - uses: actions/checkout@v4
      - name: Disable AppArmor
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - run: dart --version
      - run: dart pub get
      - run: dart analyze --fatal-infos .
      - run: dart example/download_chrome.dart
      - run: xvfb-run --auto-servernum dart test -P ci --platform vm
        if: runner.os == 'Linux'
        env:
          PUPPETEER_SKIP_GOLDEN_COMPARISON: 'true'
      - run: dart test -P ci --platform vm
        if: runner.os == 'Windows'
        env:
          PUPPETEER_SKIP_GOLDEN_COMPARISON: 'true'
      - run: dart test -P ci --platform vm
        if: runner.os == 'macOS'
      - run: dart tool/prepare_submit.dart
      - name: "check for uncommitted changes"
        run: |
          git diff --exit-code --stat -- . \
          || (echo "##[error] found changed files after build. please run 'dart tool/prepare_submit.dart'" \
                   "and check in all changes" \
              && exit 1)
        shell: bash
